[tool.poetry]
name = "longbi"
version = "0.1.0"
description = ""
authors = ["jebi <aedara@uw.edu>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
